const Strings = {
  FIND_FOOD_MENU: 'Find food menu click here',
  APPROVED_FOOD_LIST: 'Approved Food List',
  SEARCH_PLACEHOLDER: 'Trying searching fat, sauces names...',
  LOGIN: 'Login',
  ENTER_USER_NAME: 'Enter username/ mobile number',
  ENTER_PASSWORD: 'Enter password',
  FORGOT_PASSWORD: 'Forgot Password ?',
  SIGN_UP: 'Sign Up',
  ERROR_MSG_USER_NAME: 'Please enter Username / Mobile number',
  ERROR_MSG_PASSWORD: 'Please enter password',
  ERROR_LOGIN: 'Please check your user name / password.',
  ALREADY_HAVE_A_C: 'Already have a account?',
  DONT_HAVE_ACCOUNT: "Don't have account?",
  CREATE_A_NEW_ACCOUNT: 'create a new account',
  ENTER_USER_NAME_L: 'Enter username',
  ENTER_NAME: 'Enter name',
  ENTER_MOBILE: 'Enter mobile number',
  ENTER_EMAIL_ID: 'Enter email ID',
  ENTER_CONFIRM_PASS: 'Enter confirm password',
  COMINGS_SOON: 'Comings soon',
  PASSWORD_VALIDATE: 'Please enter strong password',
  PLEASE_ADD_MaNDATORY_FIELD: 'Please enter mandatory field.',
  DASHBOARD: 'Dashboard',
};

export default Strings;
